permalink: /:categories/:title

collections:
  clients:
    output: true
    permalink: /:collection/:name/
  works:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
    values:
      layout: "default"
